export default function(){

  return {
    endless: {projectName: "Endless",
              imageList: ['shipOne.jpg', 'shipTwo.gif', 'shipThree.jpeg'],
              description: "2D Online Multiplayer Game",
              demoURL: 'https://www.youtube.com/embed/NHCpUvQA9uE'},
   blinkspbj: {projectName: "Blinks PB&J",
              imageList: ['blink.jpg', 'poop.gif', 'biscuit.jpg'],
              description: "2D Mobile Unity Game",
              demoURL: 'none'},
    swordfishspacesystems: {projectName: "Swordfish Space Systems",
              imageList: ['fuck.jpg'],
              description: "Unity User Interface",
              demoURL: 'https://www.youtube.com/embed/K9Ecu2H1Q3g'},
    armorindex: {projectName: "Armor Index",
              imageList: ['armorindex.jpg'],
              description: "Web User Interface",
              demoURL: 'none'},
    mintcushions: {projectName: "Mintcushions",
              imageList: ['mint.jpg'],
              description: "Full Stack Web Application",
              demoURL: 'none'},
    gameworld: {projectName: "Game World",
              imageList: ['gameworld.jpg'],
              description: "Computer Graphics Application",
              demoURL: 'https://www.youtube.com/embed/VQ3e0xYQzr8'},
    findingscott: {projectName: "Finding Scott",
              imageList: ['findingscott.jpg'],
              description: "2D Unity Platformer Game",
              demoURL: 'none'},
    miscellaneous: {projectName: "Miscellaneous Art",
              imageList: ['misc.jpg'],
              description: "All miscellaneous art",
              demoURL: 'none'},
    wintersoldier: {projectName: "WinterSoldier UI",
              imageList: ['wintersoldier.jpg'],
              description: "Flash User Interface Engine",
              demoURL: 'https://www.youtube.com/embed/-Tf08yUNjIc'},
  };

}
