export default function(){

  return {
    endless: {projectName: "Endless",
              imageList: ['FreeForAll_eahov4',  'Clank_lh7adc',  'Lockon_uq2pns','mecha_sngcps','Abiter_lf8vxz',
              'TeamDeath_pjmnus','UI_main_select_buasod',  'Souleater_bdiljg',  'Jupiter_nmfokt',  'UI_team_select_ce7onv',
              'UI_main_fhykzf',  'UI_team_uaafhj','360_rsjiuv','ONE_kkut9u','PS4_vjzekd'],
              description: "2D Online Multiplayer Game",
              demoURL: 'https://www.youtube.com/embed/NHCpUvQA9uE',
              programming: false,
              repository: 'empty'},
   blinkspbj: {projectName: "Blinks PB&J",
              imageList: ['blink.jpg', 'poop.gif', 'biscuit.jpg'],
              description: "2D Mobile Unity Game",
              demoURL: 'none',
              programming: true,
              repository: 'null'},
   swordfishspacesystems: {projectName: "Swordfish Space Systems",
              imageList: ['Swordfish_icon_lyiaw5','titan1_c5y3rs','titan2_xgq9ke','joystick1_bgdedi',
              'joystick2_mjbw5z','joystick3_pjxy5q'],
              description: "Unity User Interface",
              demoURL: 'https://www.youtube.com/embed/K9Ecu2H1Q3g',
              programming: false,
              repository: 'empty'},
    armorindex: {projectName: "Armor Index",
              imageList: ['fallout_icon_uqhgl6','fallout_map_n0mbzl','ArmorIndex_icons_werpl3'],
              description: "Web User Interface",
              demoURL: 'https://www.youtube.com/embed/LpPGKVyW28Q',
              programming: false,
              repository: 'empty'},
    mintcushions: {projectName: "Mintcushions",
              imageList: ['amanda_psllo7', 'erik_pijv5p', 'mintLogo_pic7uq'],
              description: "Full Stack Web Application",
              demoURL: 'https://www.youtube.com/embed/t0cYLDhtxTw',
              programming: false,
              repository: 'empty'},
    gameworld: {projectName: "Game World",
              imageList: ['gameworld.jpg'],
              description: "Computer Graphics Application",
              demoURL: 'https://www.youtube.com/embed/VQ3e0xYQzr8',
              programming: false,
              repository: 'empty'},
    findingscott: {projectName: "Finding Scott",
              imageList: ['idleAnimation_nxpcfo','runningAnimation_vz1rhs'],
              description: "2D Unity Platformer Game",
              demoURL: 'none',
              programming: false,
              repository: 'empty'},
    miscellaneous: {projectName: "Miscellaneous Art",
              imageList: ['whitewolf_axinxh'],
              description: "All miscellaneous art",
              demoURL: 'none',
              programming: false,
              repository: 'empty'},
    wintersoldier: {projectName: "WinterSoldier UI",
              imageList: ['skullMask_cow8zs','bullets_csuosf','icons_gfktdz','gun_mzmang'],
              description: "Flash User Interface Engine",
              demoURL: 'https://www.youtube.com/embed/-Tf08yUNjIc',
              programming: false,
              repository: 'empty'}
  };

}
